services:
  pe:
    build:
      context: "./app"
    image: git-service.ait.ac.at:8010/sct-slotmachine-public/harmonic-public/pe-controller
    ports:
      - "80:8000"
    environment:
      - PEERS={"A":"http://mpc1:8420","B":"http://mpc2:8421","C":"http://mpc3:8422"}
      - ENCODER=http://enc:8642
  mpc1:
    build:
      context: "./mpc"
    image: git-service.ait.ac.at:8010/sct-slotmachine-public/harmonic-public/mpc_node
    environment:
      - ID=0
      - PARTIES=["mpc1", "mpc2", "mpc3"]
      - ALGORITHM=${ALGO}
    expose:
      - "5000"
      - "8420"
    cap_add:
      - NET_ADMIN
  mpc2:
    build:
      context: "./mpc"
    # image: git-service.ait.ac.at:8010/sct-slotmachine-public/harmonic-public/mpc_node
    environment:
      - ID=1
      - PARTIES=["mpc1", "mpc2", "mpc3"]
      - ALGORITHM=${ALGO}
    expose:
      - "5001"
      - "8421"
    cap_add:
      - NET_ADMIN
  mpc3:
    build:
      context: "./mpc"
    # image: git-service.ait.ac.at:8010/sct-slotmachine-public/harmonic-public/mpc_node
    environment:
      - ID=2
      - PARTIES=["mpc1", "mpc2", "mpc3"]
      - ALGORITHM=${ALGO}
    expose:
      - "5002"
      - "8422"
    cap_add:
      - NET_ADMIN
  enc:
    build:
      context : "./enc"
    image: git-service.ait.ac.at:8010/sct-slotmachine-public/harmonic-public/pe-enc
    environment:
      - ALGORITHM=${ALGO}
    expose:
      - "8642"
    ports:
      - "88:8642"
